# This workflow pushes changes to production.
# By kuflierl with ❤️
name: Release and Push

on:
  push:
    branches: [ main ]

permissions:
  actions: read
  checks: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get some info
      id: vars
      run: |
        base_version=$(cat app.properties | grep "BASE_VERSION" | cut -d '=' -f 2)
        build_number=$(($(git tag | grep $base_version | wc -l) + 1))
        release_tag="$base_version-$build_number"
        echo "release tag: $release_tag"
        echo "::set-output name=base_version::$base_version"
        echo "::set-output name=build_number::$build_number"
        echo "::set-output name=release_tag::$release_tag"

    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.release_tag }}
        name: Automatic Release ${{ steps.vars.outputs.release_tag }}
        body: |
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Trigger Update api
      id: api_trigger
      env:
        API_URL: ${{ secrets.UPDATE_URL }}
        API_SECRET: ${{ secrets.UPDATE_TOKEN }}
      run: |
        set -e
        sh -c "curl --silent --show-error --fail -H 'auth: $API_SECRET' '$API_URL'"
